trigger:
  - main

pool:
  vmImage: 'ubuntu-latest'

variables:
  dockerRegistryServiceConnection: 'dockerhub-connection'
  imageRepository: 'konopus/ci_cd_lab1'
  tag: '$(Build.BuildId)'

stages:
  - stage: BuildAndTest
    displayName: 'Збирання та Тестування'
    jobs:
      - job: BuildJob
        displayName: 'Build & Unit Tests'
        steps:
      
          - task: NodeTool@0
            inputs:
              versionSpec: '20.x'
            displayName: 'Install Node.js'

          - script: |
              npm install
              npm run build
            displayName: 'Install dependencies & Build TypeScript'

          - script: |
              npm run test
            displayName: 'Run Unit Tests'

  - stage: DockerBuildAndPublish
    displayName: 'Docker: Збірка та Публікація'
    dependsOn: BuildAndTest
    jobs:
      - job: DockerJob
        displayName: 'Docker Build & Push'
        steps:
          
          - task: Docker@2
            displayName: 'Build and push Docker image'
            inputs:
              command: 'buildAndPush'
              repository: '$(imageRepository)'
              dockerfile: '**/Dockerfile'
              containerRegistry: '$(dockerRegistryServiceConnection)'
              tags: |
                $(tag)
                latest