name: CI/CD

on:
  push:
    branches:
      - main
      - 'feature/**'
      - 'bugfix/**'
    paths-ignore:
      - 'docs/**'
      - 'README.md'

jobs:
  build-and-test:
    name: Build & Unit Tests
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Install Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20.x'

      - name: Install dependencies & Build TypeScript
        run: |
          npm install
          npm run build

      - name: Run Unit Tests
        run: npm run test

  docker-build-and-publish:
    needs: build-and-test
    uses: ./.github/workflows/docker-pack-n-push.yaml
    with:
      repository: konopus/ci_cd_lab1
      tag: ${{ github.run_number }}
      push: ${{ github.ref == 'refs/heads/main' }}
      latest: ${{ github.ref == 'refs/heads/main' }}
    secrets: inherit
